In [1]:
import pandas as pd
import matplotlib.pyplot as plt  
import pandas as pd  
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split , KFold
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

from collections import Counter

import pickle
import numpy as np

from sklearn.tree import DecisionTreeRegressor

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import sklearn.metrics as sm

import math
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
from sklearn.model_selection import KFold

from sklearn.model_selection import StratifiedKFold

import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
np.set_printoptions(suppress=True)

In [2]:
# Loading the Model
dt = pickle.load(open('/content/_DT.pkl', "rb"))

In [3]:
f = pd.read_csv('/content/features2.csv')

In [4]:
t = pd.read_csv('/content/targets2.csv')

In [5]:
f.head()

Project_No  Are_there_bookworms_in_your_family?  \
0        2948                                    1   
1        3021                                    1   
2        3033                                    0   
3        3034                                    1   
4        3036                                    1   

   Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?  \
0                                                  0                                                              
1                                                  0                                                              
2                                                  0                                                              
3                                                  0                                                              
4                                                  0                                                              

   Do_you_need_a_place_of_worship_in_your_house?  \
0                                              0   
1                                              1   
2                                              1   
3                                              1   
4                                              1   

   Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?  \
0                                                  1                                    
1                                                  0                                    
2                                                  1                                    
3                                                  0                                    
4                                                  1                                    

   How_many_members_are_there_in_your_family?  \
0                                           2   
1                                           4   
2                                           3   
3                                           3   
4                                           2   

   How_often_do_you_use_the_kitchen?  How_often_do_you_work_from_home?  \
0                                  0                                 2   
1                                  1                                 2   
2                                  0                                 1   
3                                  1                                 2   
4                                  0                                 1   

   Is_there_anything_you_are_bringing_with_you_to_your_new_home_from_your_old_house?_Other_than_furniture.  \
0                                                  1                                                         
1                                                  1                                                         
2                                                  0                                                         
3                                                  0                                                         
4                                                  1                                                         

   Nature_of_the_space.  ...  White_secondary_bedroom  Reds_secondary_bedroom  \
0                     0  ...                        0                       0   
1                     0  ...                        0                       0   
2                     0  ...                        0                       0   
3                     0  ...                        0                       0   
4                     0  ...                        0                       0   

   Grey_secondary_bedroom  We_like_to_socialize_outside_the_house.  \
0                       1                                        1   
1                       0                                        1   
2                       0                

In [ ]:
a = []

In [ ]:
a

[]

In [ ]:
d = f.iloc[1]

In [ ]:
d

Project_No  Are_there_bookworms_in_your_family?  \
0        2948                                    1   

   Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?  \
0                                                  0                                                              

   Do_you_need_a_place_of_worship_in_your_house?  \
0                                              0   

   Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?  \
0                                                  1                                    

   How_many_members_are_there_in_your_family?  \
0                                           2   

   How_often_do_you_use_the_kitchen?  How_often_do_you_work_from_home?  \
0                                  0                                 2   

   Is_there_anything_you_are_bringing_with_you_to_your_new_home_from_your_old_house?_Other_than_furniture.  \
0                                                  1                                                         

   Nature_of_the_space.  ...  White_secondary_bedroom  Reds_secondary_bedroom  \
0                     0  ...                        0                       0   

   Grey_secondary_bedroom  We_like_to_socialize_outside_the_house.  \
0                       1                                        1   

   We_appreciate_private_spaces_in_our_home.  \
0                                          1   

   We_love_hosting_parties_at_home.  The_family_likes_to_gather_together.  \
0                                 0                                     0   

   We_love_the_outdoors.  We_like_to_stay_at_home.  _Style_  
0                      1                         1        8  

[1 rows x 77 columns]

In [ ]:
d.shape

(1, 77)

In [ ]:
len(a)

77

In [ ]:
f.shape

(2574, 77)

In [ ]:
f.columns

Index(['Project_No', 'Are_there_bookworms_in_your_family?',
       'Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?',
       'Do_you_need_a_place_of_worship_in_your_house?',
       'Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?',
       'How_many_members_are_there_in_your_family?',
       'How_often_do_you_use_the_kitchen?', 'How_often_do_you_work_from_home?',
       'Is_there_anything_you_are_bringing_with_you_to_your_new_home_from_your_old_house?_Other_than_furniture.',
       'Nature_of_the_space.', 'What_is_the_purpose_of_your_space?',
       'What_would_be_the_height_of_the_person_using_the_kitchen?_(This_information_will_help_us_design_the_space_more_ergonomically)',
       'Would_you_be_using_any_of_your_old_furniture?',
       'Does_anyone_in_the_family_have_a_hobby_that_needs_a_specific_place_for_work_and_storage?',
       'What_kind_of_lighting_do_you_prefer_for_your_Bedroom?',
 

In [ ]:
prediction = dt.predict(d)

In [ ]:
prediction

array([1])

In [12]:
d1 = f.iloc[3:4]

In [13]:
d1

Project_No  Are_there_bookworms_in_your_family?  \
3        3034                                    1   

   Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?  \
3                                                  0                                                              

   Do_you_need_a_place_of_worship_in_your_house?  \
3                                              1   

   Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?  \
3                                                  0                                    

   How_many_members_are_there_in_your_family?  \
3                                           3   

   How_often_do_you_use_the_kitchen?  How_often_do_you_work_from_home?  \
3                                  1                                 2   

   Is_there_anything_you_are_bringing_with_you_to_your_new_home_from_your_old_house?_Other_than_furniture.  \
3                                                  0                                                         

   Nature_of_the_space.  ...  White_secondary_bedroom  Reds_secondary_bedroom  \
3                     0  ...                        0                       0   

   Grey_secondary_bedroom  We_like_to_socialize_outside_the_house.  \
3                       1                                        1   

   We_appreciate_private_spaces_in_our_home.  \
3                                          0   

   We_love_hosting_parties_at_home.  The_family_likes_to_gather_together.  \
3                                 0                                     1   

   We_love_the_outdoors.  We_like_to_stay_at_home.  _Style_  
3                      1                         1       11  

[1 rows x 77 columns]

In [15]:
d1.shape

(1, 77)

In [16]:
prediction2 = dt.predict(d1)

In [17]:
prediction2

array([2])

In [30]:
f.loc[f['_Style_'] == 2]

Project_No  Are_there_bookworms_in_your_family?  \
300         3802                                    1   
352         3940                                    0   
453         4284                                    1   
577         3409                                    0   
601         3430                                    0   
...          ...                                  ...   
2078        4587                                    0   
2079        3420                                    0   
2080        3434                                    0   
2083        4490                                    0   
2085        3452                                    0   

      Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?  \
300                                                   0                                                              
352                                                   0                                                              
453                                                   0                                                              
577                                                   0                                                              
601                                                   0                                                              
...                                                 ...                                                              
2078                                                  0                                                              
2079                                                  0                                                              
2080                                                  0                                                              
2083                                                  0                                                              
2085                                                  0                                                              

      Do_you_need_a_place_of_worship_in_your_house?  \
300                                               1   
352                                               1   
453                                               1   
577                                               1   
601                                               1   
...                                             ...   
2078                                              1   
2079                                              1   
2080                                              1   
2083                                              1   
2085                                              1   

      Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?  \
300                                                   0                                    
352                                                   0                                    
453                                                   0                                    
577                                                   0                                    
601                                                   0                                    
...                                                 ...                                    
2078                                                  0                                    
2079                                                  0                                    
2080                                                  0                                    
2083                                                  1                                    
2085                                                  0                                    

      How_many_members_are_there_in_your_family?  \
300                                            3   
352                               

In [21]:
d2 = f.iloc[2268:2269]

In [22]:
d2

Project_No  Are_there_bookworms_in_your_family?  \
2268        3295                                    0   

      Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?  \
2268                                                  0                                                              

      Do_you_need_a_place_of_worship_in_your_house?  \
2268                                              0   

      Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?  \
2268                                                  1                                    

      How_many_members_are_there_in_your_family?  \
2268                                           2   

      How_often_do_you_use_the_kitchen?  How_often_do_you_work_from_home?  \
2268                                  0                                 2   

      Is_there_anything_you_are_bringing_with_you_to_your_new_home_from_your_old_house?_Other_than_furniture.  \
2268                                                  0                                                         

      Nature_of_the_space.  ...  White_secondary_bedroom  \
2268                     0  ...                        0   

      Reds_secondary_bedroom  Grey_secondary_bedroom  \
2268                       0                       0   

      We_like_to_socialize_outside_the_house.  \
2268                                        0   

      We_appreciate_private_spaces_in_our_home.  \
2268                                          1   

      We_love_hosting_parties_at_home.  The_family_likes_to_gather_together.  \
2268                                 0                                     0   

      We_love_the_outdoors.  We_like_to_stay_at_home.  _Style_  
2268                      0                         0       17  

[1 rows x 77 columns]

In [23]:
prediction3 = dt.predict(d2)

In [24]:
prediction3

array([1])

In [26]:
d3 = f.iloc[403:404]

In [27]:
d3

Project_No  Are_there_bookworms_in_your_family?  \
403        4093                                    1   

     Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?  \
403                                                  0                                                              

     Do_you_need_a_place_of_worship_in_your_house?  \
403                                              1   

     Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?  \
403                                                  0                                    

     How_many_members_are_there_in_your_family?  \
403                                           5   

     How_often_do_you_use_the_kitchen?  How_often_do_you_work_from_home?  \
403                                  1                                 2   

     Is_there_anything_you_are_bringing_with_you_to_your_new_home_from_your_old_house?_Other_than_furniture.  \
403                                                  0                                                         

     Nature_of_the_space.  ...  White_secondary_bedroom  \
403                     0  ...                        1   

     Reds_secondary_bedroom  Grey_secondary_bedroom  \
403                       0                       0   

     We_like_to_socialize_outside_the_house.  \
403                                        0   

     We_appreciate_private_spaces_in_our_home.  \
403                                          1   

     We_love_hosting_parties_at_home.  The_family_likes_to_gather_together.  \
403                                 0                                     1   

     We_love_the_outdoors.  We_like_to_stay_at_home.  _Style_  
403                      1                         1       27  

[1 rows x 77 columns]

In [28]:
prediction3 = dt.predict(d3)

In [29]:
prediction3

array([2])

In [33]:
d4 = f.iloc[601:602]

In [34]:
d4

Project_No  Are_there_bookworms_in_your_family?  \
601        3430                                    0   

     Are_you_looking_for_any_special_accessibility_needs,_such_as_a_loved_one_who_needs_a_walker_or_a_wheelchair?  \
601                                                  0                                                              

     Do_you_need_a_place_of_worship_in_your_house?  \
601                                              1   

     Do_you_or_anyone_in_your_family_have_a_collection_that_you_would_like_to_show_off?  \
601                                                  0                                    

     How_many_members_are_there_in_your_family?  \
601                                           4   

     How_often_do_you_use_the_kitchen?  How_often_do_you_work_from_home?  \
601                                  0                                 0   

     Is_there_anything_you_are_bringing_with_you_to_your_new_home_from_your_old_house?_Other_than_furniture.  \
601                                                  0                                                         

     Nature_of_the_space.  ...  White_secondary_bedroom  \
601                     0  ...                        0   

     Reds_secondary_bedroom  Grey_secondary_bedroom  \
601                       0                       0   

     We_like_to_socialize_outside_the_house.  \
601                                        0   

     We_appreciate_private_spaces_in_our_home.  \
601                                          0   

     We_love_hosting_parties_at_home.  The_family_likes_to_gather_together.  \
601                                 1                                     0   

     We_love_the_outdoors.  We_like_to_stay_at_home.  _Style_  
601                      0                         1        2  

[1 rows x 77 columns]

In [36]:
prediction4 = dt.predict(d4)

In [37]:
prediction4

array([0])